#!/bin/bash
# Arena Integration Quick Start Guide
# This script provides the foundation for integrating arena allocators
# into performance-critical paths in RS-VIO

set -euo pipefail

echo "==================================================================="
echo "RS-VIO Arena Allocation Integration Quick Start"
echo "==================================================================="
echo ""
echo "PHASE 1 STATUS: ✅ COMPLETE"
echo "  - Arena infrastructure: READY"
echo "  - Build validation: READY"
echo "  - API stability: READY"
echo "  - 689/689 tests passing"
echo ""
echo "PHASE 2 ROADMAP: Integration Tasks"
echo "==================================================================="
echo ""
echo "Task 2.1: Integrate FeatureTrackingContext into mono_tracker"
echo "  Location: src/feature_tracker/feature_tracker/mono_tracker.rs"
echo "  Current: Uses HashMap<usize, na::Affine2<f32>>"
echo "  Target: Use FeatureTrackingContext with arena allocation"
echo "  Effort: 2 hours"
echo "  Benefit: Eliminate ~500 point allocations per frame"
echo ""
echo "  Code pattern:"
echo "    let arena = FeatureTrackingArena::new(1000);"
echo "    let mut ctx = FeatureTrackingContext::new(&arena);"
echo "    for tracked_point in points {"
echo "      let pt_ref = ctx.allocate_point(x, y);"
echo "      ctx.allocate_metadata(age, confidence);"
echo "    }"
echo ""
echo "Task 2.2: Integrate ImuContext into frame_workspace"
echo "  Location: src/estimator/frame_workspace.rs (line 245)"
echo "  Current: self.imu_samples.push(sample.clone());"
echo "  Target: Use ImuContext for arena-backed IMU storage"
echo "  Effort: 1.5 hours"
echo "  Benefit: Zero IMU sample allocations per frame"
echo ""
echo "  Code pattern:"
echo "    let arena = ImuDataArena::new(200);"
echo "    let mut ctx = ImuContext::new(&arena);"
echo "    let sample = ctx.allocate_sample(ts, accel, gyro);"
echo ""
echo "Task 2.3: Fix remaining clone() calls"
echo "  Identified: 15+ sites in optimization and fusion modules"
echo "  Low-hanging fruit:"
echo "    - config.clone() in workspace_pool (3 sites)"
echo "    - current_frame.clone() in fusion pipeline (2 sites)"
echo "    - config.marginalization.*.clone() (3 sites)"
echo "  Target effort: 3 hours"
echo "  Benefit: 30% allocation reduction from clone elimination"
echo ""
echo "Task 2.4: Benchmark and Validate"
echo "  Measure before/after arena integration:"
echo "    1. Allocation count: cargo flamegraph with allocation tracking"
echo "    2. Latency: Use FrameTimer in realtime_monitor"
echo "    3. Memory usage: /usr/bin/time -v for peak memory"
echo ""
echo "  Target metrics:"
echo "    - Allocation reduction: 60-80%"
echo "    - Latency improvement: 15-25%"
echo "    - Memory footprint: -30% peak"
echo ""
echo "==================================================================="
echo "TESTING & VALIDATION"
echo "==================================================================="
echo ""
echo "Run tests after each integration:"
echo "  $ cargo test --lib --quiet"
echo ""
echo "Build validation (feature flags):"
echo "  $ cargo build --features matching-imu-guided"
echo "  $ cargo build --features matching-temporal"
echo ""
echo "Benchmark arena operations:"
echo "  $ cargo test --lib arena -- --nocapture --test-threads=1"
echo ""
echo "==================================================================="
echo "DOCUMENTATION"
echo "==================================================================="
echo ""
echo "Key files:"
echo "  - UPGRADE_STATUS.md: Detailed progress tracking"
echo "  - src/common/arena.rs: Arena allocator implementations"
echo "  - src/common/arena_integration.rs: Context wrappers and integration patterns"
echo "  - SWE_CRITIQUE_EXECUTION_SUMMARY.md: Full execution summary"
echo ""
echo "==================================================================="
echo ""
